module.exports = {
  Organization: require('./Organization'),
  User: require('./User'),
  BiometricTemplate: require('./BiometricTemplate'),
  Site: require('./Site'),
  Shift: require('./Shift'),
  ShiftAssignment: require('./ShiftAssignment'),
  ShiftSwapRequest: require('./ShiftSwapRequest'),
  WeeklyOffConfig: require('./WeeklyOffConfig'),
  AttendanceLog: require('./AttendanceLog'),
  Timesheet: require('./Timesheet'),
  LeaveType: require('./LeaveType'),
  LeaveBalance: require('./LeaveBalance'),
  LeaveRequest: require('./LeaveRequest'),
  Policy: require('./Policy'),
  ScheduledReport: require('./ScheduledReport'),
  Agency: require('./Agency'),
  Job: require('./Job'),
  ActivityPunch: require('./ActivityPunch'),
  OvertimeRecord: require('./OvertimeRecord'),
  AuditLog: require('./AuditLog'),
  AnomalyRecord: require('./AnomalyRecord'),
  Notification: require('./Notification'),
  ApiKey: require('./ApiKey'),
  Webhook: require('./Webhook'),
};
